fix: resolve conflict of type\Page and meta\Page
These two classes having the same name caused an error that on some
pages, after saving the page, the page itself remained blank.
The error-log contained the following:

[Mon Nov 28 09:05:52 2016] [error] [client 91.65.183.141] PHP Fatal
error:  Cannot use dokuwiki\\plugin\\struct\\types\\Page as Page because
the name is already in use in
[...]/lib/plugins/struct/meta/Search.php on line 7,
referer: [...]